#!/bin/bash
target="192.168.18.134"
runtime=20
for i in $(seq 10 18); do
  wsize=$( echo 2^$i | bc )
  output=$(netperf -H $target -l $runtime -- -S $wsize)
  echo $output | awk '{print $23 " " $27}' >> $1
done
